import PIL.Image
import PIL.Hdf5StubImagePlugin
import PIL.FitsStubImagePlugin
import PIL.SunImagePlugin
import PIL.GbrImagePlugin
import PIL.PngImagePlugin
import PIL.MicImagePlugin
import PIL.FpxImagePlugin
import PIL.PcxImagePlugin
import PIL.ImImagePlugin
import PIL.SpiderImagePlugin
import PIL.PsdImagePlugin
import PIL.BufrStubImagePlugin
import PIL.SgiImagePlugin
import PIL.McIdasImagePlugin
import PIL.XpmImagePlugin
import PIL.BmpImagePlugin
import PIL.TgaImagePlugin
import PIL.PalmImagePlugin
import PIL.XVThumbImagePlugin
import PIL.GribStubImagePlugin
import PIL.ArgImagePlugin
import PIL.PdfImagePlugin
import PIL.ImtImagePlugin
import PIL.GifImagePlugin
import PIL.CurImagePlugin
import PIL.WmfImagePlugin
import PIL.MpegImagePlugin
import PIL.IcoImagePlugin
import PIL.TiffImagePlugin
import PIL.PpmImagePlugin
import PIL.MspImagePlugin
import PIL.EpsImagePlugin
import PIL.JpegImagePlugin
import PIL.PixarImagePlugin
import PIL.PcdImagePlugin
import PIL.IptcImagePlugin
import PIL.XbmImagePlugin
import PIL.DcxImagePlugin
import PIL.IcnsImagePlugin
import PIL.FliImagePlugin
