import Image
import Hdf5StubImagePlugin 
import FitsStubImagePlugin 
import SunImagePlugin 
import GbrImagePlugin 
import PngImagePlugin 
import MicImagePlugin 
import FpxImagePlugin 
import PcxImagePlugin 
import ImImagePlugin 
import SpiderImagePlugin 
import PsdImagePlugin 
import BufrStubImagePlugin 
import SgiImagePlugin 
import McIdasImagePlugin 
import XpmImagePlugin 
import BmpImagePlugin 
import TgaImagePlugin 
import PalmImagePlugin 
import XVThumbImagePlugin 
import GribStubImagePlugin 
import ArgImagePlugin 
import PdfImagePlugin 
import ImtImagePlugin 
import GifImagePlugin 
import CurImagePlugin 
import WmfImagePlugin 
import MpegImagePlugin 
import IcoImagePlugin 
import TiffImagePlugin 
import PpmImagePlugin 
import MspImagePlugin 
import EpsImagePlugin 
import JpegImagePlugin 
import PixarImagePlugin 
import PcdImagePlugin 
import IptcImagePlugin 
import XbmImagePlugin 
import DcxImagePlugin 
import IcnsImagePlugin 
import FliImagePlugin
print "ID", Image.ID
