#!/bin/bash
#
# CellProfiler is distributed under the GNU General Public License.
# See the accompanying file LICENSE for details.
#
# Copyright (c) 2003-2009 Massachusetts Institute of Technology
# Copyright (c) 2009-2014 Broad Institute
# All rights reserved.
#
# Please see the AUTHORS file for credits.
#
# Website: http://www.cellprofiler.org
#

if [ -d /Applications/CPAnalyst.app ]; then
    mv /Applications/CPAnalyst.app /Applications/CellProfiler\ Analyst.app
fi
